version: "3.5"
services:

  # ####################################################################################################################
  # User Management service
  # ####################################################################################################################
#  usermanagement:
#    build:
#      context: user-management
#    container_name: "users"
#    ports:
#      - 3001:3001
#    depends_on:
#      - mongo

  # ####################################################################################################################
  # Recommender service
  # ####################################################################################################################
  recommender:
    build:
      context: recommender
    container_name: "recommender"
    ports:
      - 3000:3000

  # ####################################################################################################################
  # Mongo DB instance
  # ####################################################################################################################
  mongo:
    image: mongo
    container_name: "mongoDB"
    ports:
      - 27017:27017
    volumes:
      - /data/users